version: '3'
services:
  mysql:
    restart: always
    image: mysql:8.0.31
    container_name: mysql-master
    volumes:
      - /etc/my.cnf: //c/my.cnf
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=root"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306

 