version: '3'
services:
  mysql:
    restart: always
    image: mysql:8.0.31
    container_name: mysql-master
    volumes:
      - /etc/my.cnf:\Users\Administrator\Desktop\spring-learn\compose-file\mysql-master
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=root"
      - "TZ=Asia/Shanghai"
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 3306:3306